export const routeNames = {
  Marketing:'marketing',
  SignUp: 'SignUp',
  Register: 'Register',
  AccountVerification:'AccountVerification',
  LoginScreen:'LoginScreen',
  OtpScreen: 'OtpScreen',
  ResetPassword: 'ResetPassword',
  ForgotPassword: 'ForgotPassword',
  bottomTabNavigator: 'BottomTabNavigator',
  Profile: 'Profile',
  ProfileRegistration:'ProfileRegistration',
    home: 'Home',
OrderScreen:"Order's",
EarningScreen:'Earnings',
}as const;
